const sStart = ""; const sEnd = ""; const filename = ""; const cloneCanvas = {innerHTML: ""}; const document = {getElementById: () => ({innerHTML: ""})};
                "const htmlStr = [",
                    "<!DOCTYPE html>",
                    "<html lang='ja'>",
                    "<head>",
                    "<meta charset='UTF-8'>",
                    "<title>平面図レイアウト調整 - " + filename + "</title>",
                    "<style>",
                    "  body { margin: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #525659; display: flex; flex-direction: column; height: 100vh; overflow: hidden; }",
                    "  .print-toolbar { background: #282828; color: white; padding: 10px 15px; display: flex; align-items: center; gap: 15px; flex-wrap: wrap; box-shadow: 0 2px 5px rgba(0,0,0,0.5); z-index: 100; flex-shrink: 0; }",
                    "  .print-toolbar select, .print-toolbar input { padding: 4px 6px; border-radius: 4px; border: none; font-size: 13px; color: #000; }",
                    "  button { background: #355E8B; color: white; border: none; padding: 6px 12px; border-radius: 4px; cursor: pointer; font-size: 13px; font-weight: bold; }",
                    "  button:hover { opacity: 0.9; }",
                    "  button.btn-green { background: #217270; }",
                    "  button.btn-purple { background: #725684; }",
                    "  .print-workspace { flex: 1; overflow: auto; display: flex; justify-content: center; align-items: flex-start; padding: 40px; position: relative; }",
                    "  .print-canvas-container { position: relative; background: #fff; box-shadow: 0 4px 15px rgba(0,0,0,0.5); flex-shrink: 0; overflow: hidden; margin-bottom: 40px; transform-origin: top center; transition: transform 0.15s ease-out; }",
                    "  .print-canvas-layer { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }",
                    "  .print-draggable { position: absolute; cursor: move; transform-origin: top left; user-select: none; -webkit-user-select: none; }",
                    "  .print-hover-outline { transition: outline 0.2s, outline-offset 0.2s; outline: 2px dashed transparent; outline-offset: 4px; }",
                    "  .print-hover-outline:hover { outline-color: #3b82f6; outline-offset: 2px; }",
                    "  .svg-draggable { cursor: move; pointer-events: auto; }",
                    "  .svg-draggable:hover { opacity: 0.6; }",
                    "  .pl-table-title { background: #f0f0f0; padding: 3px 5px; font-weight: bold; font-size: 12px; border-bottom: 2px solid #333; text-align: center; color: #000; }",
                    "  .pl-table { border-collapse: collapse; font-size: 12px; border-style: hidden; width: 100%; margin: 0; color: #000; background: #fff; }",
                    "  .pl-table th, .pl-table td { border: 1px solid #333; padding: 4px 6px; white-space: nowrap; color: #000; text-align: center; font-weight: normal; }",
                    "  .pl-table th { background: transparent; }",
                    "  .pl-attr-table { width: 100%; margin: 0; border: none; border-collapse: collapse; font-size: 12px; color: #000; background: #fff; }",
                    "  .pl-attr-table th, .pl-attr-table td { border: 1px solid #333; padding: 4px 6px; white-space: nowrap; color: #000; text-align: left; font-weight: normal; }",
                    "  .pl-box { background: #fff; border: 2px solid #333; }",
                    "  .print-help-bar { position: absolute; bottom: 0; left: 0; width: 100%; background: rgba(0,0,0,0.7); color: white; text-align: center; padding: 6px; font-size: 13px; z-index: 100; pointer-events: none; }",
                    "  @media print {",
                    "      body { background: #fff; display: block; height: auto; overflow: visible; -webkit-print-color-adjust: exact; print-color-adjust: exact; }",
                    "      .print-toolbar, .print-help-bar { display: none !important; }",
                    "      .print-workspace { padding: 0 !important; display: block; overflow: visible; }",
                    "      .print-canvas-container { box-shadow: none !important; margin: 0 !important; page-break-after: avoid; page-break-inside: avoid; transform: none !important; }",
                    "      .print-hover-outline { outline: none !important; }",
                    "      .svg-draggable { cursor: default; opacity: 1 !important; }",
                    "  }",
                    "</style>",
                    "<style id='dynamicStyle'></style>",
                    "</head>",
                    "<body>",
                    "    <div class='print-toolbar'>",
                    "        <div style='display:flex; align-items:center; gap:4px;'>",
                    "            <label style='font-size:13px;'>📄 用紙:</label>",
                    "            <select id='paperSize'><option value='A4' selected>A4</option><option value='A3'>A3</option><option value='A2'>A2</option><option value='A1'>A1</option><option value='A0'>A0</option></select>",
                    "            <select id='paperOrient'><option value='landscape' selected>横</option><option value='portrait'>縦</option></select>",
                    "        </div>",
                    "        <div style='display:flex; align-items:center; gap:4px; margin-left: 10px;'>",
                    "            <label style='font-size:13px;'>🔍 縮尺: 1 /</label>",
                    "            <input type='number' id='scale' value='1000' style='width: 70px;'>",
                    "            <button id='btnAutoScale' style='padding: 4px 8px; font-size: 11px;'>自動調整</button>",
                    "        </div>",
                    "        <div style='display:flex; align-items:center; gap:4px; margin-left: 10px;'>",
                    "            <label style='font-size:13px;'>📑 表折り返し:</label>",
                    "            <select id='tableWrap'><option value='0'>なし</option><option value='20'>20行</option><option value='30'>30行</option><option value='50' selected>50行</option></select>",
                    "        </div>",
                    "        <div style='display:flex; align-items:center; gap:4px; margin-left: 10px;'>",
                    "            <label style='font-size:13px;'>ファイル名:</label>",
                    "            <input type='text' id='filename' value='" + filename + "' style='width: 180px;'>",
                    "        </div>",
                    "        <div style='display:flex; align-items:center; gap:4px; margin-left: 10px;'>",
                    "            <label style='font-size:13px;'>表示:</label>",
                    "            <button id='btnFitView' style='padding: 2px 8px; font-size: 11px; background: #3b82f6;' title='画面サイズに合わせて全体を表示'>フィット</button>",
                    "            <button id='btnZoomOut' style='padding: 2px 8px; font-size: 14px; background: #64748b;' title='縮小'>－</button>",
                    "            <span id='zoomLevel' style='font-size: 13px; width: 40px; text-align: center;'>100%</span>",
                    "            <button id='btnZoomIn' style='padding: 2px 8px; font-size: 14px; background: #64748b;' title='拡大'>＋</button>",
                    "            <label style='font-size:13px; margin-left: 10px; cursor: pointer;'><input type='checkbox' id='chkBgMap'> 背景地図</label>",
                    "        </div>",
                    "        <div style='flex: 1;'></div>",
                    "        <button id='btnPrint' class='btn-green'>🖨️ 印刷する</button>",
                    "        <button id='btnExportHtml' class='btn-purple'>📄 HTML保存</button>",
                    "    </div>",
                    "    <div class='print-workspace' id='workspace'>",
                    "        <div class='print-canvas-container' id='canvasWrap'>",
                    "            <div id='bg-map' class='print-canvas-layer' style='z-index:0; display:none;'></div>",
                    "            <div id='canvas' class='print-canvas-layer' style='z-index:1;'></div>",
                    "        </div>",
                    "    </div>",
                    "    <div class='print-help-bar'>💡 表や図面、方位記号をドラッグで自由に移動できます。背景ホイールで用紙全体を、表の上のホイールで表の拡大縮小が可能です。文字要素（区画名など）もドラッグで微調整できます。Ctrl+Pでも印刷できます。</div>",
                    sStart,
                    "    const APP_DATA = " + appDataStr + ";",
                    "    const COLORS = " + colorsStr + ";",
                    "    ",
                    "    class GeoUtils {",
                    "        static LAT_DEG_PER_METER = 1 / 111111;",
                    "        static getLonDegPerMeter(lat) { return this.LAT_DEG_PER_METER / Math.cos(lat * Math.PI / 180); }",
                    "        static m2ToHa(sqMeters) { return Math.round(((sqMeters / 10000) + Number.EPSILON) * 10000) / 10000; }",
                    "    }",
                    "    const els = {",
                    "        paperSize: document.getElementById('paperSize'),",
                    "        paperOrient: document.getElementById('paperOrient'),",
                    "        scale: document.getElementById('scale'),",
                    "        btnAutoScale: document.getElementById('btnAutoScale'),",
                    "        tableWrap: document.getElementById('tableWrap'),",
                    "        filename: document.getElementById('filename'),",
                    "        btnPrint: document.getElementById('btnPrint'),",
                    "        btnExport: document.getElementById('btnExportHtml'),",
                    "        canvasWrap: document.getElementById('canvasWrap'),",
                    "        canvas: document.getElementById('canvas'),",
                    "        chkBgMap: document.getElementById('chkBgMap'),",
                    "        dynamicStyle: document.getElementById('dynamicStyle'),",
                    "        workspace: document.getElementById('workspace')",
                    "    };",
                    "    const positions = {};",
                    "    function calcAutoScale() {",
                    "        let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;",
                    "        const p0 = APP_DATA.points[0];",
                    "        const lonDegPerMeter = GeoUtils.getLonDegPerMeter(p0.lat);",
                    "        APP_DATA.points.forEach(p => {",
                    "            const x = (p.lng - p0.lng) / lonDegPerMeter;",
                    "            const y = -(p.lat - p0.lat) / GeoUtils.LAT_DEG_PER_METER;",
                    "            if (x < minX) minX = x; if (x > maxX) maxX = x;",
                    "            if (y < minY) minY = y; if (y > maxY) maxY = y;",
                    "        });",
                    "        const w = maxX - minX || 10;",
                    "        const h = maxY - minY || 10;",
                    "        const pad = Math.max(w, h) * 0.05;",
                    "        const paperSize = els.paperSize.value;",
                    "        const paperOrient = els.paperOrient.value;",
                    "        const paperDims = { 'A4': [210, 297], 'A3': [297, 420], 'A2': [420, 594], 'A1': [594, 841], 'A0': [841, 1189] };",
                    "        let [paperW_mm, paperH_mm] = paperDims[paperSize] || [210, 297];",
                    "        if (paperOrient === 'landscape') { const tmp = paperW_mm; paperW_mm = paperH_mm; paperH_mm = tmp; }",
                    "        const availableW_m = (paperW_mm - 20) / 1000;",
                    "        const availableH_m = (paperH_mm - 20) / 1000;",
                    "        const reqScaleW = (w + pad*2) / availableW_m;",
                    "        const reqScaleH = (h + pad*2) / availableH_m;",
                    "        const reqScale = Math.max(reqScaleW, reqScaleH);",
                    "        const predefinedScales = [100, 200, 300, 400, 500, 600, 1000, 2000, 3000, 4000, 5000, 6000];",
                    "        els.scale.value = predefinedScales.find(s => s >= reqScale) || 6000;",
                    "    }",
                    "    function renderCanvas() {",
                    "        els.canvas.innerHTML = '';",
                    "        const paperSize = els.paperSize.value;",
                    "        const paperOrient = els.paperOrient.value;",
                    "        const scaleVal = parseFloat(els.scale.value) || 1000;",
                    "        let wrapLimit = parseInt(els.tableWrap.value, 10);",
                    "        els.dynamicStyle.textContent = '@page { size: ' + paperSize + ' ' + paperOrient + '; margin: 0; }';",
                    "        const paperDims = { 'A4': [210, 297], 'A3': [297, 420], 'A2': [420, 594], 'A1': [594, 841], 'A0': [841, 1189] };",
                    "        let [paperW_mm, paperH_mm] = paperDims[paperSize] || [210, 297];",
                    "        if (paperOrient === 'landscape') { const tmp = paperW_mm; paperW_mm = paperH_mm; paperH_mm = tmp; }",
                    "        const paperW_px = paperW_mm * 3.7795;",
                    "        const paperH_px = paperH_mm * 3.7795;",
                    "        els.canvas.style.width = paperW_px + 'px';",
                    "        els.canvas.style.height = paperH_px + 'px';",
                    "        let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;",
                    "        const localPoints = {};",
                    "        const p0 = APP_DATA.points[0];",
                    "        const lonDegPerMeter = GeoUtils.getLonDegPerMeter(p0.lat);",
                    "        APP_DATA.points.forEach(p => {",
                    "            const x = (p.lng - p0.lng) / lonDegPerMeter;",
                    "            const y = -(p.lat - p0.lat) / GeoUtils.LAT_DEG_PER_METER;",
                    "            localPoints[p.id] = { x, y, name: p.name };",
                    "            if (x < minX) minX = x; if (x > maxX) maxX = x;",
                    "            if (y < minY) minY = y; if (y > maxY) maxY = y;",
                    "        });",
                    "        const w = maxX - minX || 10;",
                    "        const h = maxY - minY || 10;",
                    "        const pad = Math.max(w, h) * 0.05;",
                    "        const pxPerMeter = (1000 / scaleVal) * 3.7795;",
                    "        const svgW_px = (w + pad*2) * pxPerMeter;",
                    "        const svgH_px = (h + pad*2) * pxPerMeter;",
                    "        const viewBox = (minX - pad) + ' ' + (minY - pad) + ' ' + (w + pad*2) + ' ' + (h + pad*2);",
                    "        const fontSize = 12 / pxPerMeter;",
                    "        const strokeW = 1.5 / pxPerMeter;",
                    "        const radius = 3.5 / pxPerMeter;",
                    "        let svgInner = '';",
                    "        APP_DATA.areas.forEach((area, i) => {",
                    "            let areaSvg = '';",
                    "            const coordsToLocal = (coords) => coords.map(c => ((c[1] - p0.lng) / lonDegPerMeter) + ',' + (-(c[0] - p0.lat) / GeoUtils.LAT_DEG_PER_METER)).join(' ');",
                    "            areaSvg += '<polygon points=\"' + coordsToLocal(area.coords) + '\" fill=\"' + COLORS.polyFill + '\" fill-opacity=\"0.2\" stroke=\"none\" />';",
                    "            area.holes.forEach(hole => areaSvg += '<polygon points=\"' + coordsToLocal(hole.coords) + '\" fill=\"#fff\" stroke=\"none\" />');",
                    "            svgInner += '<g>' + areaSvg + '</g>';",
                    "            const cx = (area.center.lng - p0.lng) / lonDegPerMeter;",
                    "            const cy = -(area.center.lat - p0.lat) / GeoUtils.LAT_DEG_PER_METER;",
                    "            svgInner += '<g class=\"svg-draggable\">' +",
                    "                '<rect x=\"' + (cx - fontSize*2.5) + '\" y=\"' + (cy - fontSize*1.2) + '\" width=\"' + (fontSize*5) + '\" height=\"' + (fontSize*2.6) + '\" fill=\"#fff\" fill-opacity=\"0.9\" stroke=\"' + COLORS.polyBorder + '\" stroke-width=\"' + (strokeW*0.5) + '\" />' +",
                    "                '<text x=\"' + cx + '\" y=\"' + (cy - fontSize*0.1) + '\" font-size=\"' + fontSize + '\" font-family=\"sans-serif\" text-anchor=\"middle\" fill=\"#0f766e\">区画 ' + (i+1) + '</text>' +",
                    "                '<text x=\"' + cx + '\" y=\"' + (cy + fontSize*1.1) + '\" font-size=\"' + fontSize + '\" font-family=\"sans-serif\" text-anchor=\"middle\" fill=\"#0f766e\">' + GeoUtils.m2ToHa(area.netArea).toFixed(4) + 'ha</text>' +",
                    "            '</g>';",
                    "            area.holes.forEach((hole, j) => {",
                    "                const hx = (hole.center.lng - p0.lng) / lonDegPerMeter;",
                    "                const hy = -(hole.center.lat - p0.lat) / GeoUtils.LAT_DEG_PER_METER;",
                    "                svgInner += '<g class=\"svg-draggable\">' +",
                    "                    '<rect x=\"' + (hx - fontSize*2.5) + '\" y=\"' + (hy - fontSize*1.2) + '\" width=\"' + (fontSize*5) + '\" height=\"' + (fontSize*2.6) + '\" fill=\"#fff\" fill-opacity=\"0.9\" stroke=\"' + COLORS.danger + '\" stroke-width=\"' + (strokeW*0.5) + '\" />' +",
                    "                    '<text x=\"' + hx + '\" y=\"' + (hy - fontSize*0.1) + '\" font-size=\"' + fontSize + '\" font-family=\"sans-serif\" text-anchor=\"middle\" fill=\"#A13D44\">除地 ' + (j+1) + '</text>' +",
                    "                    '<text x=\"' + hx + '\" y=\"' + (hy + fontSize*1.1) + '\" font-size=\"' + fontSize + '\" font-family=\"sans-serif\" text-anchor=\"middle\" fill=\"#A13D44\">' + GeoUtils.m2ToHa(hole.area).toFixed(4) + 'ha</text>' +",
                    "                '</g>';",
                    "            });",
                    "        });",
                    "        if(APP_DATA.customLines) {",
                    "            APP_DATA.customLines.forEach(l => {",
                    "                const pts = l.latlngs.map(p => ((p[1] - p0.lng) / lonDegPerMeter) + ',' + (-(p[0] - p0.lat) / GeoUtils.LAT_DEG_PER_METER)).join(' ');",
                    "                const w = (l.weight || 2) * (strokeW / 2);",
                    "                const c = l.color || '#333333';",
                    "                const dash = l.dashArray ? ' stroke-dasharray=\"' + l.dashArray + '\"' : '';",
                    "                svgInner += '<g><polyline points=\"' + pts + '\" fill=\"none\" stroke=\"' + c + '\" stroke-width=\"' + w + '\" stroke-linecap=\"round\" stroke-linejoin=\"round\"' + dash + ' /></g>';",
                    "            });",
                    "        }",
                    "        APP_DATA.edges.forEach(e => {",
                    "            const p1 = localPoints[e.from], p2 = localPoints[e.to];",
                    "            if (p1 && p2) svgInner += '<g><line x1=\"' + p1.x + '\" y1=\"' + p1.y + '\" x2=\"' + p2.x + '\" y2=\"' + p2.y + '\" stroke=\"' + COLORS.line + '\" stroke-width=\"' + strokeW + '\" stroke-linecap=\"round\" stroke-linejoin=\"round\" /></g>';",
                    "        });",
                    "        APP_DATA.points.forEach(p => {",
                    "            const lp = localPoints[p.id];",
                    "            svgInner += '<g><circle cx=\"' + lp.x + '\" cy=\"' + lp.y + '\" r=\"' + radius + '\" fill=\"#fff\" stroke=\"' + COLORS.pointBorder + '\" stroke-width=\"' + (strokeW * 0.8) + '\" /></g>';",
                    "            svgInner += '<g class=\"svg-draggable\"><text x=\"' + (lp.x + radius*1.5) + '\" y=\"' + (lp.y - radius*1.5) + '\" font-size=\"' + (fontSize*0.9) + '\" font-family=\"sans-serif\" fill=\"#333\">' + lp.name + '</text></g>';",
                    "        });",
                    "        if(APP_DATA.customTexts) {",
                    "            APP_DATA.customTexts.forEach(t => {",
                    "                const x = (t.lng - p0.lng) / lonDegPerMeter;",
                    "                const y = -(t.lat - p0.lat) / GeoUtils.LAT_DEG_PER_METER;",
                    "                const fs = (t.fontSize || 16) * (strokeW / 4);",
                    "                const color = t.color || '#000000';",
                    "                const rot = t.rotation || 0;",
                    "                const lines = t.text.split('\\n');",
                    "                let textSvg = '';",
                    "                lines.forEach((line, idx) => {",
                    "                    textSvg += '<text x=\"0\" y=\"' + (idx * fs * 1.5) + '\" font-size=\"' + fs + '\" font-family=\"sans-serif\" font-weight=\"bold\" fill=\"' + color + '\" stroke=\"#fff\" stroke-width=\"' + (strokeW * 0.5) + '\" paint-order=\"stroke\">' + line + '</text>';",
                    "                });",
                    "                svgInner += '<g class=\"svg-draggable\" transform=\"translate(' + x + ',' + y + ') rotate(' + rot + ')\">' + textSvg + '</g>';",
                    "            });",
                    "        }",
                    "        const svgHtml = '<svg width=\"' + svgW_px + 'px\" height=\"' + svgH_px + 'px\" viewBox=\"' + viewBox + '\" style=\"overflow:visible; background:transparent;\">' + svgInner + '</svg>';",
                    "        let totalLength = 0;",
                    "        APP_DATA.edges.forEach(e => {",
                    "            const p1 = APP_DATA.points.find(p=>p.id===e.from), p2 = APP_DATA.points.find(p=>p.id===e.to);",
                    "            if(p1 && p2) totalLength += Math.sqrt(Math.pow((p2.lng - p1.lng) / GeoUtils.getLonDegPerMeter((p1.lat + p2.lat) / 2), 2) + Math.pow((p2.lat - p1.lat) / GeoUtils.LAT_DEG_PER_METER, 2));",
                    "        });",
                    "        if (wrapLimit === 0) wrapLimit = APP_DATA.points.length || 1;",
                    "        let tableHtml = '<div style=\"display:flex; gap:10px; background:transparent;\">';",
                    "        for (let i = 0; i < APP_DATA.points.length; i += wrapLimit) {",
                    "            const chunk = APP_DATA.points.slice(i, i + wrapLimit);",
                    "            tableHtml += '<div class=\"pl-box\"><div class=\"pl-table-title\">成 果 表</div><table class=\"pl-table\">' +",
                    "                '<thead><tr><th style=\"background:transparent;\">測点名</th><th style=\"background:transparent;\">緯度</th><th style=\"background:transparent;\">経度</th></tr></thead>' +",
                    "                '<tbody>' + chunk.map(p => '<tr><td>' + p.name + '</td><td style=\"text-align:right;\">' + p.lat.toFixed(8) + '</td><td style=\"text-align:right;\">' + p.lng.toFixed(8) + '</td></tr>').join('') + '</tbody></table></div>';",
                    "        }",
                    "        tableHtml += '</div>';",
                    "        let attrRows = APP_DATA.attributes.map(a => '<tr><th style=\"background:#f0f0f0; width:80px;\">' + a.name + '</th><td style=\"width:150px;\">' + a.value + '</td></tr>').join('');",
                    "        attrRows += '<tr><th style=\"background:#f0f0f0;\">縮尺</th><td>1 / ' + scaleVal.toLocaleString() + '</td></tr>';",
                    "        const attrHtml = '<div class=\"pl-box\"><table class=\"pl-attr-table\">' + attrRows + '</table></div>';",
                    "        let areaRows = APP_DATA.areas.map((a, idx) => {",
                    "            let row = '<tr><td>区画 ' + (idx+1) + '</td><td style=\"text-align:right;\">' + GeoUtils.m2ToHa(a.netArea).toFixed(4) + ' ha</td></tr>';",
                    "            if (a.holes.length > 0) row += a.holes.map((h, j) => '<tr><td style=\"padding-left:15px; color:#c00;\">(内 除地' + (j+1) + '</td><td style=\"text-align:right; color:#c00;\">' + GeoUtils.m2ToHa(h.area).toFixed(4) + ' ha)</td></tr>').join('');",
                    "            return row;",
                    "        }).join('');",
                    "        let totalArea = APP_DATA.areas.reduce((sum, a) => sum + GeoUtils.m2ToHa(a.netArea), 0);",
                    "        areaRows += '<tr style=\"border-top:1px solid #333; font-weight:bold;\"><td>合計</td><td style=\"text-align:right;\">' + totalArea.toFixed(4) + ' ha</td></tr>';",
                    "        const areaHtml = '<div class=\"pl-box\"><div class=\"pl-table-title\">面 積 表</div><table class=\"pl-table\" style=\"min-width:180px;\">' + areaRows + '</table></div>';",
                    "        const summaryHtml = '<div class=\"pl-box\" style=\"padding: 5px 10px; font-size: 13px;\">面積合計: ' + totalArea.toFixed(4) + 'ha &nbsp;&nbsp; 測線長合計: ' + totalLength.toFixed(1) + 'm</div>';",
                    "        const compassHtml = '<div style=\"text-align:center; font-weight:bold; font-family:sans-serif; margin-bottom:-2px; font-size:18px; color:#333;\">N</div>' +",
                    "            '<svg width=\"30\" height=\"40\" viewBox=\"0 0 30 40\"><polygon points=\"15,0 8,20 22,20\" fill=\"#333\"/><line x1=\"15\" y1=\"20\" x2=\"15\" y2=\"40\" stroke=\"#333\" stroke-width=\"2\"/><line x1=\"0\" y1=\"30\" x2=\"30\" y2=\"30\" stroke=\"#333\" stroke-width=\"1\"/></svg>';",
                    "        const createPlElement = (id, content, defaultPosFn) => {",
                    "            const el = document.createElement('div'); el.className = 'print-draggable print-hover-outline'; el.id = id; el.innerHTML = content;",
                    "            el.setAttribute('data-scale', '1'); el.style.opacity = '0'; els.canvasWrap.appendChild(el);",
                    "            setTimeout(() => {",
                    "                const state = positions[id];",
                    "                if (state) {",
                    "                    el.style.left = state.left; el.style.top = state.top;",
                    "                    if (state.scale) { el.style.transform = 'scale(' + state.scale + ')'; el.setAttribute('data-scale', state.scale); }",
                    "                } else {",
                    "                    const b = el.getBoundingClientRect(); const p = els.canvas.getBoundingClientRect(); const pos = defaultPosFn(b, p);",
                    "                    el.style.left = pos.left + 'px'; el.style.top = pos.top + 'px';",
                    "                    if (pos.scale) { el.style.transform = 'scale(' + pos.scale + ')'; el.setAttribute('data-scale', pos.scale); }",
                    "                    positions[id] = { left: el.style.left, top: el.style.top, scale: pos.scale || 1 };",
                    "                }",
                    "                el.style.opacity = '1'; setupDraggable(el, id);",
                    "            }, 10);",
                    "        };",
                    "        createPlElement('pl-map', svgHtml, (b, p) => ({ left: (p.width - b.width) / 2, top: (p.height - b.height) / 2 }));",
                    "        createPlElement('pl-attr', attrHtml, () => ({ left: 20, top: 30 }));",
                    "        createPlElement('pl-area', areaHtml, (b, p) => {",
                    "            const attrEl = document.getElementById('pl-attr');",
                    "            const attrBottom = attrEl ? attrEl.offsetTop + attrEl.offsetHeight : 30;",
                    "            return { left: 20, top: attrBottom + 20 };",
                    "        });",
                    "        createPlElement('pl-survey', tableHtml, (b, p) => { let scale = 1; if (b.height > p.height - 60) scale = (p.height - 60) / b.height; return { left: Math.max(20, p.width - (b.width * scale) - 20), top: 30, scale: scale }; });",
                    "        createPlElement('pl-summary', summaryHtml, (b, p) => ({ left: 120, top: p.height - b.height - 30 }));",
                    "        createPlElement('pl-compass', compassHtml, (b, p) => ({ left: 50, top: p.height - b.height - 30 }));",
                    "    }",
                    "    function setupDraggable(el, id) {",
                    "        let startX, startY, initLeft, initTop;",
                    "        el.onmousedown = (e) => {",
                    "            if (e.target.tagName === 'INPUT' || e.target.tagName === 'BUTTON' || e.target.tagName === 'SELECT') return;",
                    "            if (e.target.closest('.svg-draggable')) return;",
                    "            e.stopPropagation(); e.preventDefault(); startX = e.clientX; startY = e.clientY; initLeft = el.offsetLeft; initTop = el.offsetTop;",
                    "            els.canvasWrap.querySelectorAll('.print-draggable').forEach(d => d.style.zIndex = '1'); el.style.zIndex = '10';",
                    "            const onMouseMove = (eMove) => { el.style.left = (initLeft + (eMove.clientX - startX) / currentViewScale) + 'px'; el.style.top = (initTop + (eMove.clientY - startY) / currentViewScale) + 'px'; };",
                    "            const onMouseUp = () => { document.removeEventListener('mousemove', onMouseMove); document.removeEventListener('mouseup', onMouseUp); if (!positions[id]) positions[id] = {}; positions[id].left = el.style.left; positions[id].top = el.style.top; };",
                    "            document.addEventListener('mousemove', onMouseMove); document.addEventListener('mouseup', onMouseUp);",
                    "        };",
                    "        el.addEventListener('wheel', (e) => {",
                    "            if (e.ctrlKey || e.metaKey || id === 'pl-map') return;",
                    "            e.stopPropagation();",
                    "            e.preventDefault(); let scale = parseFloat(el.getAttribute('data-scale')) || 1; scale += e.deltaY * -0.001; scale = Math.min(Math.max(0.3, scale), 5);",
                    "            el.style.transform = 'scale(' + scale + ')'; el.setAttribute('data-scale', scale);",
                    "            if (!positions[id]) positions[id] = {}; positions[id].scale = scale;",
                    "        }, {passive: false});",
                    "    }",
                    "    let activeSVGElem = null, ctmInverse = null, startTransformX = 0, startTransformY = 0, initialTransform = '';",
                    "    document.addEventListener('mousedown', (e) => {",
                    "        const draggableGroup = e.target.closest('.svg-draggable');",
                    "        if (draggableGroup) {",
                    "            e.stopPropagation(); e.preventDefault(); activeSVGElem = draggableGroup; const svg = activeSVGElem.closest('svg'); ctmInverse = svg.getScreenCTM().inverse();",
                    "            let p = svg.createSVGPoint(); p.x = e.clientX; p.y = e.clientY; p = p.matrixTransform(ctmInverse);",
                    "            activeSVGElem.setAttribute('data-start-mx', p.x); activeSVGElem.setAttribute('data-start-my', p.y);",
                    "            const transform = activeSVGElem.getAttribute('transform') || '';",
                    "            startTransformX = 0; startTransformY = 0;",
                    "            initialTransform = transform.replace(/translate\\([^)]+\\)/, '').trim();",
                    "            const match = transform.match(/translate\\(([-\\d.]+)[,\\s]+([-\\d.]+)\\)/);",
                    "            if (match) { startTransformX = parseFloat(match[1]); startTransformY = parseFloat(match[2]); }",
                    "        }",
                    "    });",
                    "    document.addEventListener('mousemove', (e) => {",
                    "        if (activeSVGElem) {",
                    "            const svg = activeSVGElem.closest('svg'); let p = svg.createSVGPoint(); p.x = e.clientX; p.y = e.clientY; p = p.matrixTransform(ctmInverse);",
                    "            const dx = (p.x - parseFloat(activeSVGElem.getAttribute('data-start-mx')));",
                    "            const dy = (p.y - parseFloat(activeSVGElem.getAttribute('data-start-my')));",
                    "            activeSVGElem.setAttribute('transform', 'translate(' + (startTransformX + dx) + ',' + (startTransformY + dy) + ') ' + initialTransform);",
                    "        }",
                    "    });",
                    "    document.addEventListener('mouseup', () => { activeSVGElem = null; });",
                    "    function exportHtmlFile() {",
                    "        const filename = els.filename.value || 'GNSStoGIS_Export';",
                    "        const paperSize = els.paperSize.value;",
                    "        const paperOrient = els.paperOrient.value;",
                    "        const cloneCanvas = els.canvasWrap.cloneNode(true);",
                    "        cloneCanvas.querySelectorAll('.print-draggable').forEach(el => el.classList.remove('print-hover-outline'));",
                    "        const sStart = '<scr' + 'ipt>'; const sEnd = '</scr' + 'ipt>';",
                    "        const htmlStr = [",
                    "            '<!DOCTYPE html>', '<html lang=\"ja\">', '<head>', '<meta charset=\"UTF-8\">', '<title>' + filename + '</title>',",
                    "            '<style>',",
                    "            '  body { margin: 0; padding: 0; font-family: \"Segoe UI\", Tahoma, Geneva, Verdana, sans-serif; background: #525659; display: flex; justify-content: center; align-items: flex-start; min-height: 100vh; }',",
                    "            '  .print-canvas-container { position: relative; width: ' + els.canvas.style.width + '; height: ' + els.canvas.style.height + '; background: #fff; box-shadow: 0 4px 15px rgba(0,0,0,0.5); overflow: hidden; margin-top: 40px; margin-bottom: 40px; flex-shrink: 0; transform: none !important; }',",
                    "            '  .print-draggable { position: absolute; transform-origin: top left; }',",
                    "            '  .pl-table-title { background: #f0f0f0; padding: 3px 5px; font-weight: bold; font-size: 12px; border-bottom: 2px solid #333; text-align: center; color:#000; }',",
                    "            '  .pl-table { border-collapse: collapse; font-size: 12px; border-style: hidden; width: 100%; margin: 0; color:#000; }',",
                    "            '  .pl-table th, .pl-table td { border: 1px solid #333; padding: 4px 6px; white-space: nowrap; color:#000; text-align: center; font-weight: normal; }',",
                    "            '  .pl-table th { background: transparent; }',",
                    "            '  .pl-attr-table { width: 100%; margin: 0; border: none; border-collapse: collapse; font-size: 12px; color:#000; }',",
                    "            '  .pl-attr-table th, .pl-attr-table td { border: 1px solid #333; padding: 4px 6px; white-space: nowrap; color:#000; text-align: left; font-weight: normal; }',",
                    "            '  .pl-box { background: #fff; border: 2px solid #333; }',",
                    "            '  .svg-draggable { cursor: default; }',",
                    "            '  .instruction-bar { position: fixed; top: 0; left: 0; right: 0; background: rgba(40,40,40,0.95); color: white; padding: 10px; font-size: 14px; z-index: 1000; text-align: center; box-shadow: 0 2px 5px rgba(0,0,0,0.3); }',",
                    "            '  @media print {',",
                    "            '     @page { size: ' + paperSize + ' ' + paperOrient + '; margin: 0; }',",
                    "            '     body { background: #fff; display: block; min-height: auto; margin: 0; padding: 0; -webkit-print-color-adjust: exact; print-color-adjust: exact; }',",
                    "            '     .print-canvas-container { box-shadow: none; margin: 0 !important; page-break-after: avoid; page-break-inside: avoid; transform: none !important; }',",
                    "            '     .instruction-bar { display: none !important; }',",
                    "            '  }',",
                    "            '</style>',",
                    "            '</head>', '<body>',",
                    "            '  <div class=\"instruction-bar\">💡 Ctrl+P（MacはCmd+P）でこの画面のまま印刷・PDF保存できます。</div>',",
                    "            '  <div class=\"print-canvas-container\">',",
                    "            cloneCanvas.innerHTML,",
                    "            '  </div>',",
                    "            '</body>', '</html>'",
                    "        ].join('\\n');",
                    "        const blob = new Blob([htmlStr], { type: 'text/html' });",
                    "        const url = URL.createObjectURL(blob);",
                    "        const a = document.createElement('a'); a.href = url; a.download = filename + '.html';",
                    "        a.click(); URL.revokeObjectURL(url);",
                    "    }",
                    "    let currentViewScale = 1;",
                    "    function updateZoom() {",
                    "        els.canvas.style.transform = 'scale(' + currentViewScale + ')';",
                    "        document.getElementById('zoomLevel').textContent = Math.round(currentViewScale * 100) + '%';",
                    "        const diffHeight = els.canvas.offsetHeight * (1 - currentViewScale);",
                    "        els.canvas.style.marginBottom = (40 - diffHeight) + 'px';",
                    "    }",
                    "    document.getElementById('btnZoomIn').addEventListener('click', () => { currentViewScale = Math.min(currentViewScale + 0.1, 3.0); updateZoom(); });",
                    "    document.getElementById('btnZoomOut').addEventListener('click', () => { currentViewScale = Math.max(currentViewScale - 0.1, 0.2); updateZoom(); });",
                    "    document.getElementById('btnFitView').addEventListener('click', () => {",
                    "        const workspace = document.getElementById('workspace');",
                    "        const availableW = workspace.clientWidth - 80; const availableH = workspace.clientHeight - 80;",
                    "        const scaleW = availableW / els.canvasWrap.offsetWidth; const scaleH = availableH / els.canvasWrap.offsetHeight;",
                    "        currentViewScale = Math.max(0.1, Math.min(scaleW, scaleH, 3.0)); updateZoom();",
                    "    });",
                    "    els.workspace.addEventListener('wheel', (e) => {",
                    "        if (e.ctrlKey || e.metaKey) return;",
                    "        e.preventDefault();",
                    "        currentViewScale += e.deltaY * -0.001;",
                    "        currentViewScale = Math.max(0.1, Math.min(currentViewScale, 3.0));",
                    "        updateZoom();",
                    "    }, {passive: false});",
                    "    els.btnAutoScale.addEventListener('click', () => { calcAutoScale(); renderCanvas(); document.getElementById('btnFitView').click(); });",
                    "    els.paperSize.addEventListener('change', () => { renderCanvas(); document.getElementById('btnFitView').click(); });",
                    "    els.paperOrient.addEventListener('change', () => { renderCanvas(); document.getElementById('btnFitView').click(); });",
                    "    els.scale.addEventListener('change', () => { renderCanvas(); document.getElementById('btnFitView').click(); });",
                    "    els.tableWrap.addEventListener('change', renderCanvas);",
                    "    els.btnPrint.addEventListener('click', () => window.print());",
                    "    els.btnExport.addEventListener('click', exportHtmlFile);",
                    "    calcAutoScale(); renderCanvas();",
                    "    setTimeout(() => document.getElementById('btnFitView').click(), 100);",
                    "    window.addEventListener('resize', () => { document.getElementById('btnFitView').click(); });",
                    sEnd
                ].join('\n');